name: Release
on:
  workflow_dispatch:
    inputs:
      release_name:
        required: true
        type: string
  schedule:
    - cron: '0 11 * * *'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Remove existing artifacts
        run: rm csv/*
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Docker image
        run: docker run --name llm-leaderboard-csv ${{ github.repository }}
      - name: Copy Docker container artifacts
        run: docker cp llm-leaderboard-csv:/home/docker/csv/ ./
      - name: Set release name as current date
        run: |
          GH_RELEASE_NAME="${{ github.event.inputs.release_name }}"
          if [ -n "${GH_RELEASE_NAME}" ]; then
            echo "RELEASE_NAME=${GH_RELEASE_NAME}" >> $GITHUB_ENV
          else
            echo "RELEASE_NAME=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          fi
      - name: Commit latest artifacts
        uses: endbug/add-and-commit@v9
        with:
          add: csv
          default_author: github_actions
          message: "auto: update csv outputs to version ${{ env.RELEASE_NAME }}"
          tag: ${{ env.RELEASE_NAME }}
      - name: Upload the latest artifacts to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "csv/*"
          makeLatest: true
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_NAME }}
